version: '3.8'

services:
  nginx-rag:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://192.168.1.250:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - CHAT_MODEL=qwen2.5:8b
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  rag-data:
    driver: local